/* ===== The Witch Atelier, legal texts, ES + EN =====
   Drafted for an Austrian sole trader selling a digital service to EU consumers.
   The bracketed fields must be filled in before the site takes real money, and
   a lawyer should read it once. See README. */
window.LEGAL = {
  // ---- fill these in; they appear everywhere the details are needed ----
  OPERATOR: 'Nicolás Saavedra Rueda',
  ADDRESS: '[street address], [postcode] [city], Austria',
  EMAIL: 'hola@thewitchatelier.com',
  VAT: '[VAT / UID number, or delete this line if not registered]',
  SITE: 'thewitchatelier.com',
  UPDATED: '25 August 2026',

  es: {
    nav: 'Legal',
    legal_h: 'Aviso legal',
    legal: [
      ['Titular del sitio',
       'Responsable: {OPERATOR}<br>Dirección: {ADDRESS}<br>Correo: <a href="mailto:{EMAIL}">{EMAIL}</a><br>{VAT}'],
      ['Objeto',
       '{SITE} ofrece tiradas de tarot gratuitas y una lectura personalizada de pago. El servicio es de entretenimiento y reflexión personal. No sustituye asesoramiento médico, psicológico, jurídico ni financiero, y no debe usarse para tomar decisiones que requieran un profesional cualificado.'],
      ['Servicio de pago y derecho de desistimiento',
       'La lectura personalizada es un contenido digital que se entrega de forma inmediata tras el pago. Al confirmar la compra, aceptas que la ejecución comience de inmediato y reconoces que pierdes el derecho de desistimiento de 14 días una vez entregada la lectura (art. 16 m de la Directiva 2011/83/UE y su transposición austriaca, FAGG §18). Si la lectura no llega por un fallo técnico, se reenvía o se devuelve el importe íntegro.'],
      ['Precios y pago',
       'Los precios se muestran en euros e incluyen los impuestos aplicables. El pago se procesa íntegramente por Stripe; este sitio no ve ni almacena datos de tu tarjeta.'],
      ['Propiedad intelectual',
       'Los textos, la baraja de 78 cartas y el diseño de este sitio son obra propia y están protegidos por derechos de autor. Las ilustraciones de las cartas son originales: no reproducen ninguna baraja existente.'],
      ['Responsabilidad',
       'El servicio se presta tal cual. No se garantiza que las lecturas sean exactas, útiles o adecuadas a un fin concreto. La responsabilidad se limita a lo que la ley permita e, en todo caso, al importe pagado por la lectura.'],
      ['Ley aplicable y reclamaciones',
       'Se aplica el derecho austriaco, sin perjuicio de los derechos que la ley del país de residencia reconozca a los consumidores. La Comisión Europea ofrece una plataforma de resolución de litigios en línea: <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener">ec.europa.eu/consumers/odr</a>. No estamos obligados ni dispuestos a participar en un procedimiento de arbitraje de consumo.'],
    ],
    privacy_h: 'Privacidad',
    privacy: [
      ['Quién trata tus datos',
       'El responsable del tratamiento es {OPERATOR}, {ADDRESS}. Para cualquier cuestión sobre tus datos escribe a <a href="mailto:{EMAIL}">{EMAIL}</a>.'],
      ['Las tiradas gratuitas no recogen nada',
       'Las tiradas gratuitas y la baraja funcionan enteramente en tu navegador. No se envía nada a ningún servidor, no hay registro, no hay analítica y no se guarda ninguna tirada. Si cierras la pestaña, no queda rastro.'],
      ['Qué recogemos si pides una lectura',
       'Solo si compras una lectura personalizada: tu nombre, fecha de nacimiento, correo electrónico, el tema elegido y el texto de tu pregunta. Esos datos se usan exclusivamente para escribir y entregarte esa lectura.'],
      ['Base jurídica',
       'El tratamiento es necesario para ejecutar el contrato que solicitas (art. 6.1 b del RGPD). No usamos tus datos para publicidad ni los vendemos a nadie.'],
      ['La consulta gratuita',
       'La consulta gratuita funciona igual, pero con menos datos: tu nombre, tu fecha de nacimiento, el género que indiques y tu pregunta se envían a <strong>Anthropic</strong> para redactar la lectura, y nada de eso se guarda en nuestros servidores ni se asocia a un correo. No pedimos correo y no hay pago, así que Stripe no interviene. Lo único que queda en tu navegador es la cookie técnica <strong>wa_free</strong> descrita en la política de cookies. Base jurídica: art. 6.1 b del RGPD, la prestación del servicio gratuito que has solicitado.'],
      ['Con quién se comparten',
       '<strong>Stripe</strong> (Irlanda/EE. UU.) procesa el pago y recibe tu correo y los datos de tu tarjeta; nosotros nunca vemos la tarjeta.<br><strong>Anthropic</strong> (EE. UU.) recibe tu pregunta y las cartas para redactar la lectura. Según sus condiciones para empresas, no se usa para entrenar modelos.<br><strong>Netlify</strong> (EE. UU.) aloja el sitio y registra direcciones IP en sus logs de servidor por seguridad.<br>Las transferencias fuera del EEE se amparan en cláusulas contractuales tipo de la Comisión Europea.'],
      ['Cuánto tiempo se conserva',
       'Tu pregunta y la lectura quedan asociadas a la sesión de pago de Stripe, que las conserva conforme a sus propios plazos y a las obligaciones contables (en Austria, siete años para los justificantes de la operación). Puedes pedir la supresión de la lectura en cualquier momento; los registros contables mínimos deben conservarse por ley.'],
      ['Decisiones automatizadas',
       'La lectura la redacta un modelo de lenguaje. Es un texto de entretenimiento y reflexión: no produce efectos jurídicos ni te afecta significativamente de modo similar, por lo que no constituye una decisión automatizada en el sentido del art. 22 del RGPD.'],
      ['Tus derechos',
       'Puedes acceder a tus datos, rectificarlos, suprimirlos, limitar u oponerte a su tratamiento y solicitar su portabilidad. Escribe a <a href="mailto:{EMAIL}">{EMAIL}</a>. También puedes reclamar ante la autoridad austriaca de protección de datos (Datenschutzbehörde, <a href="https://www.dsb.gv.at" target="_blank" rel="noopener">dsb.gv.at</a>) o ante la de tu país de residencia.'],
    ],
    cookies_h: 'Cookies',
    cookies: [
      ['Una sola cookie técnica, y solo si usas la consulta gratuita',
       'No usamos analítica, ni publicidad, ni cookies de seguimiento de ningún tipo. Solo una: si haces una consulta gratuita, guardamos una cookie llamada <strong>wa_free</strong> que únicamente lleva la cuenta de cuántas consultas has hecho hoy, para que el servicio gratuito no pueda usarse de forma abusiva. Caduca en 24 horas, no contiene datos personales, no se comparte con nadie y no sirve para reconocerte en otros sitios. Es estrictamente necesaria para prestar el servicio que has pedido, así que la ley no exige consentimiento para ella y no verás un banner.'],
      ['Lo único que se guarda en tu navegador',
       'Guardamos una sola cosa en el almacenamiento local de tu navegador: el idioma que eliges (ES o EN), para no volver a preguntártelo. No es una cookie, no se envía a ningún servidor y nadie más puede leerlo. Puedes borrarlo vaciando los datos del sitio en tu navegador.'],
      ['Sin recursos de terceros',
       'Las páginas no cargan tipografías, imágenes, vídeos ni scripts de otros dominios. Nada de lo que ves aquí hace que tu dirección IP llegue a un tercero mientras navegas.'],
      ['La excepción: el pago',
       'Si decides comprar una lectura, el pago se realiza en una página de Stripe. Stripe sí utiliza cookies propias, necesarias para procesar el pago y prevenir el fraude, y se rige por su propia política de privacidad. Eso ocurre solo si llegas a esa página.'],
    ],
  },

  en: {
    nav: 'Legal',
    legal_h: 'Legal notice',
    legal: [
      ['Site owner',
       'Operator: {OPERATOR}<br>Address: {ADDRESS}<br>Email: <a href="mailto:{EMAIL}">{EMAIL}</a><br>{VAT}'],
      ['What this site is',
       '{SITE} offers free tarot spreads and one paid personal reading. The service is for entertainment and personal reflection. It does not replace medical, psychological, legal or financial advice, and should not be used to make decisions that call for a qualified professional.'],
      ['The paid service and your right to cancel',
       'The personal reading is digital content delivered immediately after payment. By confirming the purchase you agree that performance begins at once and acknowledge that you lose the 14-day right of withdrawal once the reading has been delivered (Article 16(m) of Directive 2011/83/EU, as implemented in Austria by FAGG §18). If a reading fails to arrive for technical reasons, it is resent or refunded in full.'],
      ['Prices and payment',
       'Prices are shown in euros and include applicable tax. Payment is handled entirely by Stripe; this site never sees or stores your card details.'],
      ['Intellectual property',
       'The texts, the 78-card deck and the design of this site are original work and protected by copyright. The card illustrations are our own: they do not reproduce any existing deck.'],
      ['Liability',
       'The service is provided as is. No warranty is given that a reading is accurate, useful or fit for any particular purpose. Liability is limited to the extent the law allows and, in any case, to the amount paid for the reading.'],
      ['Governing law and complaints',
       'Austrian law applies, without prejudice to the consumer rights of your country of residence. The European Commission provides an online dispute resolution platform: <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener">ec.europa.eu/consumers/odr</a>. We are neither obliged nor willing to take part in consumer arbitration proceedings.'],
    ],
    privacy_h: 'Privacy',
    privacy: [
      ['Who handles your data',
       'The controller is {OPERATOR}, {ADDRESS}. For anything concerning your data, write to <a href="mailto:{EMAIL}">{EMAIL}</a>.'],
      ['The free spreads collect nothing',
       'The free spreads and the deck run entirely in your browser. Nothing is sent to any server, there is no signup, no analytics, and no spread is stored. Close the tab and nothing remains.'],
      ['What we collect if you order a reading',
       'Only if you buy a personal reading: your name, date of birth, email address, the topic you pick and the text of your question. That data is used solely to write and deliver that reading.'],
      ['Legal basis',
       'The processing is necessary to perform the contract you asked for (Article 6(1)(b) GDPR). We do not use your data for advertising and we do not sell it to anyone.'],
      ['The free consultation',
       'The free consultation works the same way with less data: your name, date of birth, the gender you state and your question go to <strong>Anthropic</strong> so the reading can be written, and none of it is stored on our servers or attached to an email address. We ask for no email and there is no payment, so Stripe is not involved. The only thing left in your browser is the technical <strong>wa_free</strong> cookie described in the cookie policy. Legal basis: Article 6(1)(b) GDPR, providing the free service you asked for.'],
      ['Who it is shared with',
       '<strong>Stripe</strong> (Ireland/USA) processes the payment and receives your email and card details; we never see the card.<br><strong>Anthropic</strong> (USA) receives your question and the cards drawn in order to write the reading. Under their commercial terms it is not used to train models.<br><strong>Netlify</strong> (USA) hosts the site and records IP addresses in server logs for security.<br>Transfers outside the EEA rely on the European Commission\'s standard contractual clauses.'],
      ['How long it is kept',
       'Your question and the reading stay attached to the Stripe payment session, which retains them under its own schedule and under accounting obligations (in Austria, seven years for transaction records). You can ask for the reading to be deleted at any time; the minimum accounting records must be kept by law.'],
      ['Automated decisions',
       'The reading is written by a language model. It is a text for entertainment and reflection: it produces no legal effects and does not similarly significantly affect you, so it is not an automated decision within the meaning of Article 22 GDPR.'],
      ['Your rights',
       'You may access, correct, erase, restrict or object to the processing of your data, and request portability. Write to <a href="mailto:{EMAIL}">{EMAIL}</a>. You may also complain to the Austrian data protection authority (Datenschutzbehörde, <a href="https://www.dsb.gv.at" target="_blank" rel="noopener">dsb.gv.at</a>) or to the authority in your country of residence.'],
    ],
    cookies_h: 'Cookies',
    cookies: [
      ['One technical cookie, and only if you use the free consultation',
       'We run no analytics, no advertising and no tracking cookies of any kind. There is exactly one: if you take a free consultation, we store a cookie called <strong>wa_free</strong> that does nothing but count how many consultations you have had today, so the free service cannot be abused. It expires in 24 hours, holds no personal data, is shared with nobody, and cannot be used to recognise you on other sites. It is strictly necessary to provide the service you asked for, so the law does not require consent for it and you will not see a banner.'],
      ['The one thing stored in your browser',
       'We keep exactly one thing in your browser\'s local storage: the language you chose (ES or EN), so we do not ask again. It is not a cookie, it is never sent to any server, and nobody else can read it. Clearing this site\'s data in your browser removes it.'],
      ['No third-party resources',
       'These pages load no fonts, images, video or scripts from other domains. Nothing here causes your IP address to reach a third party while you browse.'],
      ['The exception: payment',
       'If you choose to buy a reading, payment happens on a page hosted by Stripe. Stripe does set its own cookies, necessary to process the payment and prevent fraud, and is governed by its own privacy policy. That only happens if you go to that page.'],
    ],
  },

  de: {
    nav: 'Rechtliches',
    legal_h: 'Impressum',
    legal: [
      ['Anbieter',
       'Verantwortlich: {OPERATOR}<br>Anschrift: {ADDRESS}<br>E-Mail: <a href="mailto:{EMAIL}">{EMAIL}</a><br>{VAT}'],
      ['Gegenstand',
       '{SITE} bietet kostenlose Tarot-Legungen und eine kostenpflichtige persönliche Deutung. Der Dienst dient der Unterhaltung und der persönlichen Reflexion. Er ersetzt keine medizinische, psychologische, rechtliche oder finanzielle Beratung und darf nicht für Entscheidungen herangezogen werden, die in fachkundige Hände gehören.'],
      ['Kostenpflichtiger Dienst und Rücktrittsrecht',
       'Die persönliche Deutung ist ein digitaler Inhalt, der unmittelbar nach der Zahlung geliefert wird. Mit der Bestellung stimmst du ausdrücklich zu, dass mit der Ausführung sofort begonnen wird, und nimmst zur Kenntnis, dass dein 14-tägiges Rücktrittsrecht mit der Lieferung erlischt (Art. 16 lit. m der Richtlinie 2011/83/EU; in Österreich § 18 FAGG). Bleibt die Deutung aus technischen Gründen aus, wird sie erneut zugestellt oder der Betrag vollständig erstattet.'],
      ['Preise und Zahlung',
       'Die Preise verstehen sich in Euro inklusive anfallender Steuern. Die Zahlung wickelt ausschließlich Stripe ab; diese Seite sieht und speichert keine Kartendaten.'],
      ['Urheberrecht',
       'Die Texte, das Deck aus 78 Karten und die Gestaltung dieser Seite sind eigene Werke und urheberrechtlich geschützt. Die Kartenbilder sind Originale und geben kein bestehendes Deck wieder.'],
      ['Haftung',
       'Der Dienst wird wie besehen bereitgestellt. Es wird nicht zugesichert, dass eine Deutung zutreffend, nützlich oder für einen bestimmten Zweck geeignet ist. Die Haftung ist auf das gesetzlich zulässige Maß und jedenfalls auf den für die Deutung gezahlten Betrag beschränkt.'],
      ['Anwendbares Recht und Beschwerden',
       'Es gilt österreichisches Recht, unbeschadet der Verbraucherrechte deines Wohnsitzstaates. Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung bereit: <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener">ec.europa.eu/consumers/odr</a>. Zur Teilnahme an einem Verbraucherschlichtungsverfahren sind wir weder verpflichtet noch bereit.'],
    ],
    privacy_h: 'Datenschutz',
    privacy: [
      ['Wer deine Daten verarbeitet',
       'Verantwortlicher im Sinne der DSGVO ist {OPERATOR}, {ADDRESS}. Für Fragen zu deinen Daten schreib an <a href="mailto:{EMAIL}">{EMAIL}</a>.'],
      ['Die Gratis-Legungen erheben nichts',
       'Die kostenlosen Legungen und das Deck laufen vollständig in deinem Browser. Es wird nichts an einen Server gesendet, es gibt keine Anmeldung, keine Analyse, und keine Legung wird gespeichert. Schließt du den Tab, bleibt nichts zurück.'],
      ['Was wir erheben, wenn du eine Deutung bestellst',
       'Nur beim Kauf einer persönlichen Deutung: Name, Geburtsdatum, E-Mail-Adresse, das gewählte Thema und der Text deiner Frage. Diese Daten dienen ausschließlich dazu, genau diese Deutung zu schreiben und zuzustellen.'],
      ['Rechtsgrundlage',
       'Die Verarbeitung ist zur Erfüllung des von dir gewünschten Vertrags erforderlich (Art. 6 Abs. 1 lit. b DSGVO). Wir nutzen deine Daten nicht für Werbung und geben sie an niemanden weiter, der sie kaufen möchte.'],
      ['Die kostenlose Beratung',
       'Die kostenlose Beratung funktioniert genauso, nur mit weniger Daten: dein Name, dein Geburtsdatum, das angegebene Geschlecht und deine Frage gehen an <strong>Anthropic</strong>, damit die Deutung geschrieben werden kann. Nichts davon wird auf unseren Servern gespeichert oder mit einer E-Mail-Adresse verknüpft. Wir fragen keine E-Mail ab und es gibt keine Zahlung, Stripe ist also nicht beteiligt. In deinem Browser bleibt nur das technische Cookie <strong>wa_free</strong>, das in der Cookie-Richtlinie beschrieben ist. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO, die Erbringung des von dir gewünschten kostenlosen Dienstes.'],
      ['An wen sie weitergegeben werden',
       '<strong>Stripe</strong> (Irland/USA) wickelt die Zahlung ab und erhält deine E-Mail-Adresse und die Kartendaten; wir sehen die Karte nie.<br><strong>Anthropic</strong> (USA) erhält deine Frage und die gezogenen Karten, um die Deutung zu schreiben. Nach den dortigen Geschäftsbedingungen wird dies nicht zum Training von Modellen verwendet.<br><strong>Netlify</strong> (USA) hostet die Seite und protokolliert IP-Adressen zu Sicherheitszwecken.<br>Übermittlungen außerhalb des EWR stützen sich auf die Standardvertragsklauseln der Europäischen Kommission.'],
      ['Speicherdauer',
       'Deine Frage und die Deutung bleiben der Stripe-Zahlungssitzung zugeordnet und werden nach deren Fristen sowie nach den Aufbewahrungspflichten des Rechnungswesens gespeichert (in Österreich sieben Jahre für Belege). Du kannst die Löschung der Deutung jederzeit verlangen; die gesetzlich vorgeschriebenen Buchhaltungsbelege müssen erhalten bleiben.'],
      ['Automatisierte Entscheidungen',
       'Die Deutung wird von einem Sprachmodell verfasst. Sie ist ein Text zur Unterhaltung und Reflexion: sie entfaltet keine rechtliche Wirkung und beeinträchtigt dich nicht in ähnlich erheblicher Weise, stellt also keine automatisierte Entscheidung im Sinne des Art. 22 DSGVO dar.'],
      ['Deine Rechte',
       'Du hast das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch und Datenübertragbarkeit. Schreib an <a href="mailto:{EMAIL}">{EMAIL}</a>. Du kannst dich außerdem bei der österreichischen Datenschutzbehörde (<a href="https://www.dsb.gv.at" target="_blank" rel="noopener">dsb.gv.at</a>) oder der Behörde deines Wohnsitzstaates beschweren.'],
    ],
    cookies_h: 'Cookies',
    cookies: [
      ['Ein einziges technisches Cookie, und nur bei der Gratis-Beratung',
       'Wir nutzen keine Analyse, keine Werbung und keine Tracking-Cookies. Es gibt genau eines: Wenn du eine kostenlose Beratung machst, speichern wir ein Cookie namens <strong>wa_free</strong>, das nichts weiter tut, als zu zählen, wie viele Beratungen du heute hattest, damit der Gratis-Dienst nicht missbraucht werden kann. Es läuft nach 24 Stunden ab, enthält keine personenbezogenen Daten, wird an niemanden weitergegeben und kann dich auf anderen Seiten nicht wiedererkennen. Es ist zur Erbringung des von dir gewünschten Dienstes unbedingt erforderlich, daher verlangt das Gesetz dafür keine Einwilligung und du siehst kein Banner.'],
      ['Das Einzige, was im Browser gespeichert wird',
       'Wir legen genau eine Sache im lokalen Speicher deines Browsers ab: die von dir gewählte Sprache (ES, EN oder DE), damit wir nicht erneut fragen. Das ist kein Cookie, es wird an keinen Server gesendet, und niemand sonst kann es lesen. Löschst du die Daten dieser Seite im Browser, ist es weg.'],
      ['Keine Ressourcen von Dritten',
       'Diese Seiten laden keine Schriften, Bilder, Videos oder Skripte von anderen Domains. Nichts hier führt dazu, dass deine IP-Adresse beim Surfen an Dritte gelangt.'],
      ['Die Ausnahme: die Zahlung',
       'Entscheidest du dich für eine Deutung, findet die Zahlung auf einer von Stripe betriebenen Seite statt. Stripe setzt dort eigene Cookies, die für die Abwicklung und die Betrugsprävention erforderlich sind, und es gilt die dortige Datenschutzerklärung. Das geschieht nur, wenn du diese Seite auch aufrufst.'],
    ],
  },
};
